-- vim.g.nightflyTransparent = 1
-- vim.cmd [[colorscheme nightfly]]
-- require('nightfox').setup({
--   options = {
--     transparent = true,
--   }
-- })
-- vim.cmd [[colorscheme nightfox]]
-- Theme settings
vim.g.tokyonight_style = "night"
vim.g.tokyonight_italic_functions = true
vim.g.tokyonight_sidebars = { "qf", "vista_kind", "terminal", "packer" }
vim.g.tokyonight_transparent = true
vim.g.tokyonight_transparent_sidebar = true
vim.g.tokyonight_dark_float = false
vim.g.tokyonight_colors = {
  bg_float = "none"
}
vim.cmd [[colorscheme tokyonight]]
-- vim.cmd [[colorscheme gruvbox]]
-- vim.cmd 'au ColorScheme * hi! Normal guibg=none'
-- vim.g.gruvbox_invert_selection = '0'
-- require("catppuccin").setup({
--   transparent_background = true,
--   coc_nvim = false,
--   lsp_trouble = false,
--   cmp = true,
--   lsp_saga = true,
--   gitgutter = false,
--   gitsigns = true,
--   telescope = true,
--   dashboard = true,
--   neogit = true,
--   symbols_outline = true,
--   nvimtree = {
--     enabled = true,
--     show_root = false,
--     transparent_panel = false,
--   }
-- })
--
-- vim.cmd [[colorscheme catppuccin]]
-- require('rose-pine').setup({
--   --- @usage 'main' | 'moon'
--   dark_variant = 'main',
--   bold_vert_split = false,
--   dim_nc_background = false,
--   disable_background = false,
--   disable_float_background = false,
--   disable_italics = false,
--
--   --- @usage string hex value or named color from rosepinetheme.com/palette
--   groups = {
--     background = 'base',
--     panel = 'surface',
--     border = 'highlight_med',
--     comment = 'muted',
--     link = 'iris',
--     punctuation = 'subtle',
--
--     error = 'love',
--     hint = 'iris',
--     info = 'foam',
--     warn = 'gold',
--
--     headings = {
--       h1 = 'iris',
--       h2 = 'foam',
--       h3 = 'rose',
--       h4 = 'gold',
--       h5 = 'pine',
--       h6 = 'foam',
--     }
--     -- or set all headings at once
--     -- headings = 'subtle'
--   },
--
--   -- Change specific vim highlight groups
--   highlight_groups = {
--     ColorColumn = { bg = 'rose' }
--   }
-- })
--
-- -- set colorscheme after options
-- vim.cmd('colorscheme rose-pine')
-- require('kanagawa').setup({
--   undercurl = true, -- enable undercurls
--   commentStyle = "italic",
--   functionStyle = "NONE",
--   keywordStyle = "italic",
--   statementStyle = "bold",
--   typeStyle = "NONE",
--   variablebuiltinStyle = "italic",
--   specialReturn = true, -- special highlight for the return keyword
--   specialException = true, -- special highlight for exception handling keywords
--   transparent = true, -- do not set background color
--   dimInactive = false, -- dim inactive window `:h hl-NormalNC`
--   globalStatus = true, -- adjust window separators highlight for laststatus=3
--   colors = {},
--   overrides = {},
-- })
-- vim.cmd("colorscheme kanagawa")
