#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
# A cross-platform, OpenGL terminal emulator.
# https://alacritty.org

# Campbell (Windows 10 default)
colors:
  # Default colors
  cursor:
    text: '0x181818'
    cursor: '0xd8d8d8'

  primary:
    background: '0x0c0c0c'
    foreground: '0xcccccc'

  # Normal colors
  normal:
    black: '0x0c0c0c'
    red: '0xc50f1f'
    green: '0x13a10e'
    yellow: '0xc19c00'
    blue: '0x0037da'
    magenta: '0x881798'
    cyan: '0x3a96dd'
    white: '0xcccccc'

  # Bright colors
  bright:
    black: '0x767676'
    red: '0xe74856'
    green: '0x16c60c'
    yellow: '0xf9f1a5'
    blue: '0x3b78ff'
    magenta: '0xb4009e'
    cyan: '0x61d6d6'
    white: '0xf2f2f2'

live_config_reload: true

env:
  TERM: xterm-256color

shell:
  program: /usr/local/bin/fish

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

window:
  opacity: 1.00
  padding:
    x: 18
    y: 16
  dynamic_padding: false
  decorations: buttonless

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: 'SFMono Nerd Font'
    style: Medium
  size: 20.0

mouse:
  hide_when_typing: true

key_bindings:
  # Rename the current tmux window
  - { key: Comma, mods: Command, chars: "\x02\x2c" }
  # Lazygit
  - { key: G, mods: Command, chars: "\x02g" }
  # Lazydocker
  - { key: D, mods: Command, chars: "\x02K" }
  # Select a new tmux session for the attached client interactively
  - { key: K, mods: Command, chars: "\x02\x73" }
  # Select window 1-9
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }
  # Switch to last tmux session
  - { key: L, mods: Command, chars: "\x02\x4c" }
  - { key: LBracket, mods: Command, chars: "\x02\x5b" }
  # Change to the previous tmux window
  - { key: LBracket, mods: Command|Shift, chars: "\x02\x70" }
  # Split the current pane into two, left and right
  - { key: N, mods: Command|Shift, chars: "\x02\x25" }
  # Split the current pane into two, top and bottom.
  - { key: N, mods: Command, chars: "\x02\x22" }
  # Detach the current tmux client
  - { key: Q, mods: Command, chars: "\x02\x64" }
  # Change to the next tmux window
  - { key: RBracket, mods: Command|Shift, chars: "\x02\x6e" }
  # Create a new tmux window
  - { key: T, mods: Command, chars: "\x02\x63" }
  # Break the current tmux pane out of the tmux window
  - { key: T, mods: Command|Shift, chars: "\x02\x21" }
  # Kill the current tmux pane (and window if last pane)
  - { key: W, mods: Command, chars: "\x02\x78" }
  # Toggle the zoom state of the current tmux pane
  - { key: Z, mods: Command, chars: "\x02\x7a" }
