# cSpell:words alacritty lfcd
live_config_reload: true

env:
  TERM: xterm-256color

shell:
  program: /usr/local/bin/fish

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

window:
  opacity: 0.95
  padding:
    x: 18
    y: 16
  dynamic_padding: false
  decorations: buttonless

schemes:
  base16: &base16
    primary:
      background: '0x181818'
      foreground: '0xd8d8d8'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#000000'
      cursor: '0xd8d8d8'

    # Normal colors
    normal:
      black: '0x181818'
      red: '0xab4642'
      green: '0xa1b56c'
      yellow: '0xf7ca88'
      blue: '0x7cafc2'
      magenta: '0xba8baf'
      cyan: '0x86c1b9'
      white: '0xd8d8d8'

    # Bright colors
    bright:
      black: '0x585858'
      red: '0xab4642'
      green: '0xa1b56c'
      yellow: '0xf7ca88'
      blue: '0x7cafc2'
      magenta: '0xba8baf'
      cyan: '0x86c1b9'
      white: '0xf8f8f8'

  poimandres: &poimandres # Default colors
    primary:
      background: '0x1b1e28'
      foreground: '0xa6accd'

    # Cursor colors
    cursor:
      text: CellBackground
      cursor: CellForeground

    # Search colors
    #
    # Colors used for the search bar and match highlighting.
    search:
      # Allowed values are CellForeground/CellBackground, which reference the
      # affected cell, or hexadecimal colors like #ff00ff.
      matches:
        foreground: '0x1b1e28'
        background: '0xadd7ff'

      focused_match:
        foreground: '0x1b1e28'
        background: '0xadd7ff'

      bar:
        foreground: '0x1b1e28'
        background: '0xadd7ff'

    # Selection colors
    #
    # Colors which should be used to draw the selection area.
    #
    # Allowed values are CellForeground/CellBackground, which reference the
    # affected cell, or hexadecimal colors like #ff00ff.
    selection:
      text: CellForeground
      background: '0x303340'

    # Vi mode cursor colors
    #
    # Colors for the cursor when the vi mode is active.
    #
    # Allowed values are CellForeground/CellBackground, which reference the
    # affected cell, or hexadecimal colors like #ff00ff.
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground

    # Normal colors
    normal:
      black: '0x1b1e28'
      red: '0xd0679d'
      green: '0x5de4c7'
      yellow: '0xfffac2'
      blue: '0x89ddff'
      magenta: '0xfcc5e9'
      cyan: '0xadd7ff'
      white: '0xffffff'

    # Bright colors
    bright:
      black: '0xa6accd'
      red: '0xd0679d'
      green: '0x5de4c7'
      yellow: '0xfffac2'
      blue: '0xadd7ff'
      magenta: '0xfae4fc'
      cyan: '0x89ddff'
      white: '0xffffff'

  nord: &nord
    primary:
      background: '#2e3440'
      foreground: '#d8dee9'
      dim_foreground: '#a5abb6'
    cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    vi_mode_cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    selection:
      text: CellForeground
      background: '#4c566a'
    search:
      matches:
        foreground: CellBackground
        background: '#88c0d0'
      bar:
        background: '#434c5e'
        foreground: '#d8dee9'
    normal:
      black: '#3b4252'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#88c0d0'
      white: '#e5e9f0'
    bright:
      black: '#4c566a'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#8fbcbb'
      white: '#eceff4'
    dim:
      black: '#373e4d'
      red: '#94545d'
      green: '#809575'
      yellow: '#b29e75'
      blue: '#68809a'
      magenta: '#8c738c'
      cyan: '#6d96a5'
      white: '#aeb3bb'

  tokyo-night: &tokyo-night # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black: '0x32344a'
      red: '0xf7768e'
      green: '0x9ece6a'
      yellow: '0xe0af68'
      blue: '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan: '0x449dab'
      white: '0x787c99'

    # Bright colors
    bright:
      black: '0x444b6a'
      red: '0xff7a93'
      green: '0xb9f27c'
      yellow: '0xff9e64'
      blue: '0x7da6ff'
      magenta: '0xbb9af7'
      cyan: '0x0db9d7'
      white: '0xacb0d0'

  gruvbox_material: &gruvbox_material
    primary:
      background: '#353535'
      foreground: '0xdfbf8e'

    cursor:
      text: '#2e3440'
      cursor: '#ffffff'

    vi_mode_cursor:
      text: '#2e3440'
      cursor: '#ffffff'

    normal:
      black: '0x665c54'
      red: '0xea6962'
      green: '0xa9b665'
      yellow: '0xe78a4e'
      blue: '0x7daea3'
      magenta: '0xd3869b'
      cyan: '0x89b482'
      white: '0xdfbf8e'

    bright:
      black: '0x928374'
      red: '0xea6962'
      green: '0xa9b665'
      yellow: '0xe3a84e'
      blue: '0x7daea3'
      magenta: '0xd3869b'
      cyan: '0x89b482'
      white: '0xdfbf8e'

  gruvbox: &gruvbox
    primary:
      # hard contrast: background = '0x1d2021'
      background: '0x282828'
      # soft contrast: background = '0x32302f'
      foreground: '0xebdbb2'

    # Normal colors
    normal:
      black: '0x282828'
      red: '0xcc241d'
      green: '0x98971a'
      yellow: '0xd79921'
      blue: '0x458588'
      magenta: '0xb16286'
      cyan: '0x689d6a'
      white: '0xa89984'

    # Bright colors
    bright:
      black: '0x928374'
      red: '0xfb4934'
      green: '0xb8bb26'
      yellow: '0xfabd2f'
      blue: '0x83a598'
      magenta: '0xd3869b'
      cyan: '0x8ec07c'
      white: '0xebdbb2'

  latte: &latte # Default colors
    primary:
      background: '#EFF1F5' # base
      foreground: '#4C4F69' # text
      # Bright and dim foreground colors
      dim_foreground: '#4C4F69' # text
      bright_foreground: '#4C4F69' # text

    # Cursor colors
    cursor:
      text: '#EFF1F5' # base
      cursor: '#DC8A78' # rosewater
    vi_mode_cursor:
      text: '#EFF1F5' # base
      cursor: '#7287FD' # lavender

    # Search colors
    search:
      matches:
        foreground: '#EFF1F5' # base
        background: '#6C6F85' # subtext0
      focused_match:
        foreground: '#EFF1F5' # base
        background: '#40A02B' # green
      footer_bar:
        foreground: '#EFF1F5' # base
        background: '#6C6F85' # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: '#EFF1F5' # base
        background: '#DF8E1D' # yellow
      end:
        foreground: '#EFF1F5' # base
        background: '#6C6F85' # subtext0

    # Selection colors
    selection:
      text: '#EFF1F5' # base
      background: '#DC8A78' # rosewater

    # Normal colors
    normal:
      black: '#5C5F77' # subtext1
      red: '#D20F39' # red
      green: '#40A02B' # green
      yellow: '#DF8E1D' # yellow
      blue: '#1E66F5' # blue
      magenta: '#EA76CB' # pink
      cyan: '#179299' # teal
      white: '#ACB0BE' # surface2

    # Bright colors
    bright:
      black: '#6C6F85' # subtext0
      red: '#D20F39' # red
      green: '#40A02B' # green
      yellow: '#DF8E1D' # yellow
      blue: '#1E66F5' # blue
      magenta: '#EA76CB' # pink
      cyan: '#179299' # teal
      white: '#BCC0CC' # surface1

    # Dim colors
    dim:
      black: '#5C5F77' # subtext1
      red: '#D20F39' # red
      green: '#40A02B' # green
      yellow: '#DF8E1D' # yellow
      blue: '#1E66F5' # blue
      magenta: '#EA76CB' # pink
      cyan: '#179299' # teal
      white: '#ACB0BE' # surface2

    indexed_colors:
      - { index: 16, color: '#FE640B' }
      - { index: 17, color: '#DC8A78' }

  frappe: &frappe # Default colors
    primary:
      background: '#303446' # base
      foreground: '#C6D0F5' # text
      # Bright and dim foreground colors
      dim_foreground: '#C6D0F5' # text
      bright_foreground: '#C6D0F5' # text

    # Cursor colors
    cursor:
      text: '#303446' # base
      cursor: '#F2D5CF' # rosewater
    vi_mode_cursor:
      text: '#303446' # base
      cursor: '#BABBF1' # lavender

    # Search colors
    search:
      matches:
        foreground: '#303446' # base
        background: '#A5ADCE' # subtext0
      focused_match:
        foreground: '#303446' # base
        background: '#A6D189' # green
      footer_bar:
        foreground: '#303446' # base
        background: '#A5ADCE' # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: '#303446' # base
        background: '#E5C890' # yellow
      end:
        foreground: '#303446' # base
        background: '#A5ADCE' # subtext0

    # Selection colors
    selection:
      text: '#303446' # base
      background: '#F2D5CF' # rosewater

    # Normal colors
    normal:
      black: '#51576D' # surface1
      red: '#E78284' # red
      green: '#A6D189' # green
      yellow: '#E5C890' # yellow
      blue: '#8CAAEE' # blue
      magenta: '#F4B8E4' # pink
      cyan: '#81C8BE' # teal
      white: '#B5BFE2' # subtext1

    # Bright colors
    bright:
      black: '#626880' # surface2
      red: '#E78284' # red
      green: '#A6D189' # green
      yellow: '#E5C890' # yellow
      blue: '#8CAAEE' # blue
      magenta: '#F4B8E4' # pink
      cyan: '#81C8BE' # teal
      white: '#A5ADCE' # subtext0

    # Dim colors
    dim:
      black: '#51576D' # surface1
      red: '#E78284' # red
      green: '#A6D189' # green
      yellow: '#E5C890' # yellow
      blue: '#8CAAEE' # blue
      magenta: '#F4B8E4' # pink
      cyan: '#81C8BE' # teal
      white: '#B5BFE2' # subtext1

    indexed_colors:
      - { index: 16, color: '#EF9F76' }
      - { index: 17, color: '#F2D5CF' }

  macchiato: &macchiato # Default colors
    primary:
      background: '#24273A' # base
      foreground: '#CAD3F5' # text
      # Bright and dim foreground colors
      dim_foreground: '#CAD3F5' # text
      bright_foreground: '#CAD3F5' # text

    # Cursor colors
    cursor:
      text: '#24273A' # base
      cursor: '#F4DBD6' # rosewater
    vi_mode_cursor:
      text: '#24273A' # base
      cursor: '#B7BDF8' # lavender

    # Search colors
    search:
      matches:
        foreground: '#24273A' # base
        background: '#A5ADCB' # subtext0
      focused_match:
        foreground: '#24273A' # base
        background: '#A6DA95' # green
      footer_bar:
        foreground: '#24273A' # base
        background: '#A5ADCB' # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: '#24273A' # base
        background: '#EED49F' # yellow
      end:
        foreground: '#24273A' # base
        background: '#A5ADCB' # subtext0

    # Selection colors
    selection:
      text: '#24273A' # base
      background: '#F4DBD6' # rosewater

    # Normal colors
    normal:
      black: '#494D64' # surface1
      red: '#ED8796' # red
      green: '#A6DA95' # green
      yellow: '#EED49F' # yellow
      blue: '#8AADF4' # blue
      magenta: '#F5BDE6' # pink
      cyan: '#8BD5CA' # teal
      white: '#B8C0E0' # subtext1

    # Bright colors
    bright:
      black: '#5B6078' # surface2
      red: '#ED8796' # red
      green: '#A6DA95' # green
      yellow: '#EED49F' # yellow
      blue: '#8AADF4' # blue
      magenta: '#F5BDE6' # pink
      cyan: '#8BD5CA' # teal
      white: '#A5ADCB' # subtext0

    # Dim colors
    dim:
      black: '#494D64' # surface1
      red: '#ED8796' # red
      green: '#A6DA95' # green
      yellow: '#EED49F' # yellow
      blue: '#8AADF4' # blue
      magenta: '#F5BDE6' # pink
      cyan: '#8BD5CA' # teal
      white: '#B8C0E0' # subtext1

    indexed_colors:
      - { index: 16, color: '#F5A97F' }
      - { index: 17, color: '#F4DBD6' }

  mocha: &mocha # Default colors
    primary:
      background: '#1E1E2E' # base
      foreground: '#CDD6F4' # text
      # Bright and dim foreground colors
      dim_foreground: '#CDD6F4' # text
      bright_foreground: '#CDD6F4' # text

    # Cursor colors
    cursor:
      text: '#1E1E2E' # base
      cursor: '#F5E0DC' # rosewater
    vi_mode_cursor:
      text: '#1E1E2E' # base
      cursor: '#B4BEFE' # lavender

    # Search colors
    search:
      matches:
        foreground: '#1E1E2E' # base
        background: '#A6ADC8' # subtext0
      focused_match:
        foreground: '#1E1E2E' # base
        background: '#A6E3A1' # green
      footer_bar:
        foreground: '#1E1E2E' # base
        background: '#A6ADC8' # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: '#1E1E2E' # base
        background: '#F9E2AF' # yellow
      end:
        foreground: '#1E1E2E' # base
        background: '#A6ADC8' # subtext0

    # Selection colors
    selection:
      text: '#1E1E2E' # base
      background: '#F5E0DC' # rosewater

    # Normal colors
    normal:
      black: '#45475A' # surface1
      red: '#F38BA8' # red
      green: '#A6E3A1' # green
      yellow: '#F9E2AF' # yellow
      blue: '#89B4FA' # blue
      magenta: '#F5C2E7' # pink
      cyan: '#94E2D5' # teal
      white: '#BAC2DE' # subtext1

    # Bright colors
    bright:
      black: '#585B70' # surface2
      red: '#F38BA8' # red
      green: '#A6E3A1' # green
      yellow: '#F9E2AF' # yellow
      blue: '#89B4FA' # blue
      magenta: '#F5C2E7' # pink
      cyan: '#94E2D5' # teal
      white: '#A6ADC8' # subtext0

    # Dim colors
    dim:
      black: '#45475A' # surface1
      red: '#F38BA8' # red
      green: '#A6E3A1' # green
      yellow: '#F9E2AF' # yellow
      blue: '#89B4FA' # blue
      magenta: '#F5C2E7' # pink
      cyan: '#94E2D5' # teal
      white: '#BAC2DE' # subtext1

    indexed_colors:
      - { index: 16, color: '#FAB387' }
      - { index: 17, color: '#F5E0DC' }

colors: *base16

font:
  normal:
    family: 'UbuntuMono Nerd Font'
    style: Regular
  size: 22.0
  use_thin_strokes: true

mouse:
  hide_when_typing: true

key_bindings:
  # Rename the current tmux window
  - { key: Comma, mods: Command, chars: "\x02\x2c" }
  # Select a new tmux session for the attached client interactively
  - { key: K, mods: Command, chars: "\x02\x73" }
  # Select window 1-9
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }
  # Switch to last tmux session
  - { key: L, mods: Command, chars: "\x02\x4c" }
  - { key: LBracket, mods: Command, chars: "\x02\x5b" }
  # Change to the previous tmux window
  - { key: LBracket, mods: Command|Shift, chars: "\x02\x70" }
  # Split the current pane into two, left and right
  - { key: N, mods: Command|Shift, chars: "\x02\x25" }
  # Split the current pane into two, top and bottom.
  - { key: N, mods: Command, chars: "\x02\x22" }
  # Detach the current tmux client
  - { key: Q, mods: Command, chars: "\x02\x64" }
  # Change to the next tmux window
  - { key: RBracket, mods: Command|Shift, chars: "\x02\x6e" }
  # Create a new tmux window
  - { key: T, mods: Command, chars: "\x02\x63" }
  # Break the current tmux pane out of the tmux window
  - { key: T, mods: Command|Shift, chars: "\x02\x21" }
  # Kill the current tmux pane (and window if last pane)
  - { key: W, mods: Command, chars: "\x02\x78" }
  # Toggle the zoom state of the current tmux pane
  - { key: Z, mods: Command, chars: "\x02\x7a" }
