#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
# A cross-platform, OpenGL terminal emulator.
# https://alacritty.org

colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'
  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xcd0000'
    green:   '0x00cd00'
    yellow:  '0xcdcd00'
    blue:    '0x0000ee'
    magenta: '0xcd00cd'
    cyan:    '0x00cdcd'
    white:   '0xe5e5e5'

  # Bright colors
  bright:
    black:   '0x7f7f7f'
    red:     '0xff0000'
    green:   '0x00ff00'
    yellow:  '0xffff00'
    blue:    '0x5c5cff'
    magenta: '0xff00ff'
    cyan:    '0x00ffff'
    white:   '0xffffff'

live_config_reload: true

env:
  TERM: xterm-256color

shell:
  program: /usr/local/bin/fish

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

window:
  opacity: 0.95
  padding:
    x: 18
    y: 16
  dynamic_padding: false
  decorations: buttonless

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: "Hack Nerd Font"
  italic:
    family: "Hack Nerd Font"
  bold:
    family: "Hack Nerd Font"
  bold_italic:
    family: "Hack Nerd Font"
  size: 20

mouse:
  hide_when_typing: true

option_as_alt: Both

key_bindings:
  - { key: E, mods: Command, chars: "\x02\"" } # split tmux window vertically
  - { key: E, mods: Command|Shift, chars: "\x02%" } # split tmux window horizontally
  - { key: F, mods: Command, chars: "lfcd\n" } # open file manager 'gokcehan/lf'
  - { key: F, mods: Command|Shift, chars: "\x02\x5b\x2f" } # start tmux search mode
  - { key: G, mods: Command, chars: "\x02g" } # open git manager 'jesseduffield/lazygit'
  - { key: G, mods: Command|Shift, chars: "\x02G" } # open git manager 'jesseduffield/lazygit'
  - { key: J, mods: Command, chars: "\x02\x54" } # open t - tmux smart session manager
  - { key: K, mods: Command, chars: "\x02s" } # open interactive tmux session client
  - { key: L, mods: Command, chars: "\x02L" } # switch to the last tmux session
  - { key: O, mods: Command, chars: "\x02u" } # open URLs 'joshmedeski/tmux-fzf-url'
  - { key: P, mods: Command, chars: ":GoToFile\n" } # files
  - { key: P, mods: Command|Shift, chars: ":GoToCommand\n" } # commands
  - { key: Q, mods: Command, chars: ":q\n" } # quit vim
  - { key: S, mods: Command, chars: "\x1b\x3a\x77\x0a" } # save vim buffer
  - { key: T, mods: Command, chars: "\x02c" } # create a new tmux window
  - { key: W, mods: Command, chars: "\x02x" } # kill the current pane
  - { key: Z, mods: Command, chars: "\x02z" } # toggle zoom state of the current tmux pane
  - { key: Tab, mods: Control, chars: "\x02n" } # switch to next tmux window
  - { key: Grave, mods: Control, chars: "\x02p" } # switch to previous tmux window
  - { key: Comma, mods: Command, chars: "\x02," } # rename the current tmux window
  - { key: LBracket, mods: Command, chars: "\x0f" } # navigate back in vim (ctrl+o)
  - { key: LBracket, mods: Command|Shift, chars: "\x02p" } # switch to next tmux window
  - { key: RBracket, mods: Command, chars: "\x09" } # navigate forward in vim (ctrl+i)
  - { key: RBracket, mods: Command|Shift, chars: "\x02n" } # switch to previous tmux window
  - { key: Semicolon, mods: Command, chars: "\x02:" } # enter the tmux command prompt
  - { key: Key1, mods: Command, chars: "\x021" } # select tmux window 1
  - { key: Key2, mods: Command, chars: "\x022" } #                ... 2
  - { key: Key3, mods: Command, chars: "\x023" } #                ... 3
  - { key: Key4, mods: Command, chars: "\x024" } #                ... 4
  - { key: Key5, mods: Command, chars: "\x025" } #                ... 5
  - { key: Key6, mods: Command, chars: "\x026" } #                ... 6
  - { key: Key7, mods: Command, chars: "\x027" } #                ... 7
  - { key: Key8, mods: Command, chars: "\x028" } #                ... 8
  - { key: Key9, mods: Command, chars: "\x029" } #                ... 9
