# cSpell:words alacritty lfcd
live_config_reload: true

env:
  TERM: xterm-256color

shell:
  program: /usr/local/bin/fish

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

window:
  opacity: 0.95
  padding:
    x: 18
    y: 16
  dynamic_padding: false
  decorations: buttonless

draw_bold_text_with_bright_colors: true

schemes:
  ayu: &ayu # Default colors
    cursor:
      text: '#080808'
      cursor: '#FFFFFF'

    primary:
      background: '0x0A0E14'
      foreground: '0xB3B1AD'

    # Normal colors
    normal:
      black: '0x01060E'
      red: '0xEA6C73'
      green: '0x91B362'
      yellow: '0xF9AF4F'
      blue: '0x53BDFA'
      magenta: '0xFAE994'
      cyan: '0x90E1C6'
      white: '0x424242'

    # Bright colors
    bright:
      black: '0x686868'
      red: '0xF07178'
      green: '0xC2D94C'
      yellow: '0xFFB454'
      blue: '0x59C2FF'
      magenta: '0xFFEE99'
      cyan: '0x95E6CB'
      white: '0x2a2a2a'

  nightfly: &nightfly
    # Colors
    # Default colors
    primary:
      background: '#011627'
      foreground: '#acb4c2'
      bright_foreground: '#eeeeee'

    # Cursor colors
    cursor:
      text: '#080808'
      cursor: '#3AFD9E'

    # Selection colors
    selection:
      text: '#080808'
      background: '#b2ceee'

    # Normal colors
    normal:
      black: '#1d3b53'
      red: '#fc514e'
      green: '#a1cd5e'
      yellow: '#e3d18a'
      blue: '#82aaff'
      magenta: '#c792ea'
      cyan: '#7fdbca'
      white: '#a1aab8'

    # Bright colors
    bright:
      black: '#7c8f8f'
      red: '#ff5874'
      green: '#21c7a8'
      yellow: '#ecc48d'
      blue: '#82aaff'
      magenta: '#ae81ff'
      cyan: '#7fdbca'
      white: '#d6deeb'

  mocha: &mocha # Default colors
    primary:
      background: '#1E1E2E' # base
      foreground: '#CDD6F4' # text
      # Bright and dim foreground colors
      dim_foreground: '#CDD6F4' # text
      bright_foreground: '#CDD6F4' # text

    # Cursor colors
    cursor:
      text: '#1E1E2E' # base
      cursor: '#F5E0DC' # rosewater
    vi_mode_cursor:
      text: '#1E1E2E' # base
      cursor: '#B4BEFE' # lavender

    # Search colors
    search:
      matches:
        foreground: '#1E1E2E' # base
        background: '#A6ADC8' # subtext0
      focused_match:
        foreground: '#1E1E2E' # base
        background: '#A6E3A1' # green
      footer_bar:
        foreground: '#1E1E2E' # base
        background: '#A6ADC8' # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: '#1E1E2E' # base
        background: '#F9E2AF' # yellow
      end:
        foreground: '#1E1E2E' # base
        background: '#A6ADC8' # subtext0

    # Selection colors
    selection:
      text: '#1E1E2E' # base
      background: '#F5E0DC' # rosewater

    # Normal colors
    normal:
      black: '#45475A' # surface1
      red: '#F38BA8' # red
      green: '#A6E3A1' # green
      yellow: '#F9E2AF' # yellow
      blue: '#89B4FA' # blue
      magenta: '#F5C2E7' # pink
      cyan: '#94E2D5' # teal
      white: '#BAC2DE' # subtext1

    # Bright colors
    bright:
      black: '#585B70' # surface2
      red: '#F38BA8' # red
      green: '#A6E3A1' # green
      yellow: '#F9E2AF' # yellow
      blue: '#89B4FA' # blue
      magenta: '#F5C2E7' # pink
      cyan: '#94E2D5' # teal
      white: '#A6ADC8' # subtext0

    # Dim colors
    dim:
      black: '#45475A' # surface1
      red: '#F38BA8' # red
      green: '#A6E3A1' # green
      yellow: '#F9E2AF' # yellow
      blue: '#89B4FA' # blue
      magenta: '#F5C2E7' # pink
      cyan: '#94E2D5' # teal
      white: '#BAC2DE' # subtext1

    indexed_colors:
      - { index: 16, color: '#FAB387' }
      - { index: 17, color: '#F5E0DC' }

    tmrw: &tmrw # Default colors
      primary:
        background: '0x000000'
        foreground: '0xeaeaea'

      # Normal colors
      normal:
        black: '0x000000'
        red: '0xd54e53'
        green: '0xb9ca4a'
        yellow: '0xe6c547'
        blue: '0x7aa6da'
        magenta: '0xc397d8'
        cyan: '0x70c0ba'
        white: '0x424242'

      # Bright colors
      bright:
        black: '0x666666'
        red: '0xff3334'
        green: '0x9ec400'
        yellow: '0xe7c547'
        blue: '0x7aa6da'
        magenta: '0xb77ee0'
        cyan: '0x54ced6'
        white: '0x2a2a2a'

      cursor:
        text: '#080808'
        cursor: '#FFFFFF'

    tokyo-night: &tokyo-night # Default colors
      primary:
        background: '0x222436'
        foreground: '0xc8d3f5'

      # Normal colors
      normal:
        black: '0x1b1d2b'
        red: '0xff757f'
        green: '0xc3e88d'
        yellow: '0xffc777'
        blue: '0x82aaff'
        magenta: '0xc099ff'
        cyan: '0x86e1fc'
        white: '0x828bb8'

      # Bright colors
      bright:
        black: '0x444a73'
        red: '0xff757f'
        green: '0xc3e88d'
        yellow: '0xffc777'
        blue: '0x82aaff'
        magenta: '0xc099ff'
        cyan: '0x86e1fc'
        white: '0xc8d3f5'

      indexed_colors:
        - { index: 16, color: '0xff966c' }
        - { index: 17, color: '0xc53b53' }

      cursor:
        text: '#1E1E2E' # base
        cursor: '#F5E0DC' # rosewater

      vi_mode_cursor:
        text: '#1E1E2E' # base
        cursor: '#B4BEFE' # lavender

    nord: &nord
      primary:
        background: '#2e3440'
        foreground: '#d8dee9'
        # dim_foreground: '#a5abb6'
      cursor:
        text: '#2e3440'
        cursor: '#d8dee9'
      vi_mode_cursor:
        text: '#2e3440'
        cursor: '#d8dee9'
      selection:
        text: CellForeground
        background: '#4c566a'
      search:
        matches:
          foreground: CellBackground
          background: '#88c0d0'
        footer_bar:
          background: '#434c5e'
          foreground: '#d8dee9'
      normal:
        black: '#3b4252'
        red: '#bf616a'
        green: '#a3be8c'
        yellow: '#ebcb8b'
        blue: '#81a1c1'
        magenta: '#b48ead'
        cyan: '#88c0d0'
        white: '#e5e9f0'
      bright:
        black: '#4c566a'
        red: '#bf616a'
        green: '#a3be8c'
        yellow: '#ebcb8b'
        blue: '#81a1c1'
        magenta: '#b48ead'
        cyan: '#8fbcbb'
        white: '#eceff4'
      dim:
        black: '#373e4d'
        red: '#94545d'
        green: '#809575'
        yellow: '#b29e75'
        blue: '#68809a'
        magenta: '#8c738c'
        cyan: '#6d96a5'
        white: '#aeb3bb'

colors: *tmrw

font:
  normal:
    family: 'UbuntuMono Nerd Font'
    style: Regular
  size: 22.0

mouse:
  hide_when_typing: true

key_bindings:
  # Rename the current tmux window
  - { key: Comma, mods: Command, chars: "\x02\x2c" }
  # Lazygit
  - { key: G, mods: Command, chars: "\x02g" }
  # Lazydocker
  - { key: D, mods: Command, chars: "\x02K" }
  # Select a new tmux session for the attached client interactively
  - { key: K, mods: Command, chars: "\x02\x73" }
  # Select window 1-9
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }
  # Switch to last tmux session
  - { key: L, mods: Command, chars: "\x02\x4c" }
  - { key: LBracket, mods: Command, chars: "\x02\x5b" }
  # Change to the previous tmux window
  - { key: LBracket, mods: Command|Shift, chars: "\x02\x70" }
  # Split the current pane into two, left and right
  - { key: N, mods: Command|Shift, chars: "\x02\x25" }
  # Split the current pane into two, top and bottom.
  - { key: N, mods: Command, chars: "\x02\x22" }
  # Detach the current tmux client
  - { key: Q, mods: Command, chars: "\x02\x64" }
  # Change to the next tmux window
  - { key: RBracket, mods: Command|Shift, chars: "\x02\x6e" }
  # Create a new tmux window
  - { key: T, mods: Command, chars: "\x02\x63" }
  # Break the current tmux pane out of the tmux window
  - { key: T, mods: Command|Shift, chars: "\x02\x21" }
  # Kill the current tmux pane (and window if last pane)
  - { key: W, mods: Command, chars: "\x02\x78" }
  # Toggle the zoom state of the current tmux pane
  - { key: Z, mods: Command, chars: "\x02\x7a" }
