# aki
[colors]
foreground = "#8383A5"
background = "#161720"
cursor_bg = "#B4B4AC"
cursor_border = "#EBEBE3"
cursor_fg = "#1D1E28"
selection_bg = "#EBEBE3"
selection_fg = "#1D1E28"

ansi = [
  "#161720",
  "#CA797E",
  "#A5C79F",
  "#E6B87F",
  "#F7ECE5",
  "#F5AD89",
  "#F7F9B4",
  "#EBEBE3",
]
brights = [
  "#4B4C66",
  "#CA797E",
  "#9BC2B1",
  "#E69E87",
  "#8CA1B8",
  "#AD8DBD",
  "#AF6672",
  "#DFDFD5",
]
